# Generated by Django 5.1.1 on 2024-10-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название рекламной кампании')),
                ('channel', models.CharField(max_length=300, verbose_name='Название канала продвижения')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет на рекламу')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='products.products', verbose_name='Услуга')),
            ],
        ),
    ]
