# Generated by Django 5.1.1 on 2024-09-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_profile_advertisement_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracts',
            old_name='contact_date',
            new_name='contract_date',
        ),
    ]
