# Generated by Django 5.1.1 on 2024-09-22 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_contact_date_contracts_contract_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='crm.customer'),
        ),
    ]
