# Generated by Django 5.1.1 on 2024-09-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_contracts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='period',
        ),
    ]
