# Generated by Django 5.1.1 on 2024-09-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_add_contracts_perios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Наименование продукта'),
        ),
    ]
