# Generated by Django 5.1.1 on 2024-09-22 20:06

import crm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_advertisements_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='contract_date',
            field=models.DateField(verbose_name='Дата заключения контракта'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='file',
            field=models.FileField(upload_to=crm.models.profile_file_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название контракта'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='period',
            field=models.DateField(verbose_name='Дата окончания контракта'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='crm.services', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Полная стоимость'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='crm.customer', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_advertisements', to='crm.advertisements', verbose_name='Рекламная кампания'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=300, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Отчество'),
        ),
    ]
