# Generated by Django 5.1.1 on 2024-09-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_contracts_contract_date_alter_contracts_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
