# Generated by Django 5.1.1 on 2024-10-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_advertisements', to='ads.ads', verbose_name='Рекламная кампания')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_leads', to='leads.leads', verbose_name='Потенциальный клиент')),
            ],
        ),
    ]
